-- Digital interview packs (e.g. Buyer I Master) filled in by recruiter/manager during interviews.

CREATE TABLE IF NOT EXISTS public.candidate_interview_packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    pack_key TEXT NOT NULL DEFAULT 'buyer_i_master',
    round TEXT NOT NULL DEFAULT 'first',
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    total_score NUMERIC(6,2),
    max_score NUMERIC(6,2) DEFAULT 85,
    percentage NUMERIC(6,2),
    recommendation TEXT,
    updated_by UUID REFERENCES auth.users(id),
    updated_by_email TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT candidate_interview_packs_round_check
        CHECK (round IN ('first', 'second')),
    CONSTRAINT candidate_interview_packs_recommendation_check
        CHECK (recommendation IS NULL OR recommendation IN ('yes', 'no', 'possible')),
    CONSTRAINT candidate_interview_packs_unique
        UNIQUE (candidate_id, pack_key, round)
);

CREATE INDEX IF NOT EXISTS idx_candidate_interview_packs_candidate
    ON public.candidate_interview_packs (candidate_id, pack_key, round);

ALTER TABLE public.candidate_interview_packs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Internal users can view interview packs" ON public.candidate_interview_packs;
CREATE POLICY "Internal users can view interview packs"
    ON public.candidate_interview_packs
    FOR SELECT
    USING (
        auth.role() = 'authenticated'
        AND EXISTS (
            SELECT 1
            FROM public.users u
            JOIN public.candidates c ON c.id = candidate_interview_packs.candidate_id
            WHERE u.id = auth.uid()
              AND u.role IN ('gm', 'recruiter', 'Manager', 'manager')
              AND (
                  u.role IN ('gm', 'recruiter')
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) > 0
                      AND c.position = ANY(u.allowed_positions)
                  )
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) = 0
                      AND u.department IS NOT NULL
                      AND btrim(u.department) <> ''
                      AND c.department = u.department
                  )
              )
        )
    );

DROP POLICY IF EXISTS "Internal users can insert interview packs" ON public.candidate_interview_packs;
CREATE POLICY "Internal users can insert interview packs"
    ON public.candidate_interview_packs
    FOR INSERT
    WITH CHECK (
        auth.role() = 'authenticated'
        AND EXISTS (
            SELECT 1
            FROM public.users u
            JOIN public.candidates c ON c.id = candidate_interview_packs.candidate_id
            WHERE u.id = auth.uid()
              AND u.role IN ('gm', 'recruiter', 'Manager', 'manager')
              AND (
                  u.role IN ('gm', 'recruiter')
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) > 0
                      AND c.position = ANY(u.allowed_positions)
                  )
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) = 0
                      AND u.department IS NOT NULL
                      AND btrim(u.department) <> ''
                      AND c.department = u.department
                  )
              )
        )
    );

DROP POLICY IF EXISTS "Internal users can update interview packs" ON public.candidate_interview_packs;
CREATE POLICY "Internal users can update interview packs"
    ON public.candidate_interview_packs
    FOR UPDATE
    USING (
        auth.role() = 'authenticated'
        AND EXISTS (
            SELECT 1
            FROM public.users u
            JOIN public.candidates c ON c.id = candidate_interview_packs.candidate_id
            WHERE u.id = auth.uid()
              AND u.role IN ('gm', 'recruiter', 'Manager', 'manager')
              AND (
                  u.role IN ('gm', 'recruiter')
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) > 0
                      AND c.position = ANY(u.allowed_positions)
                  )
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) = 0
                      AND u.department IS NOT NULL
                      AND btrim(u.department) <> ''
                      AND c.department = u.department
                  )
              )
        )
    )
    WITH CHECK (
        auth.role() = 'authenticated'
        AND EXISTS (
            SELECT 1
            FROM public.users u
            JOIN public.candidates c ON c.id = candidate_interview_packs.candidate_id
            WHERE u.id = auth.uid()
              AND u.role IN ('gm', 'recruiter', 'Manager', 'manager')
              AND (
                  u.role IN ('gm', 'recruiter')
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) > 0
                      AND c.position = ANY(u.allowed_positions)
                  )
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) = 0
                      AND u.department IS NOT NULL
                      AND btrim(u.department) <> ''
                      AND c.department = u.department
                  )
              )
        )
    );

GRANT SELECT, INSERT, UPDATE ON public.candidate_interview_packs TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.candidate_interview_packs_id_seq TO authenticated;
