-- Internal notes for recruiter/manager communication on candidates.
-- Notes are hidden from agency roles and visible only to internal roles.

CREATE TABLE IF NOT EXISTS public.candidate_internal_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    note_text TEXT NOT NULL,
    created_by UUID NOT NULL REFERENCES auth.users(id),
    created_by_role TEXT NOT NULL,
    created_by_email TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT candidate_internal_notes_note_text_not_empty CHECK (length(btrim(note_text)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_candidate_internal_notes_candidate_created
ON public.candidate_internal_notes (candidate_id, created_at DESC);

ALTER TABLE public.candidate_internal_notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Internal users can view candidate notes" ON public.candidate_internal_notes;
CREATE POLICY "Internal users can view candidate notes"
    ON public.candidate_internal_notes
    FOR SELECT
    USING (
        auth.role() = 'authenticated'
        AND EXISTS (
            SELECT 1
            FROM public.users u
            JOIN public.candidates c ON c.id = candidate_internal_notes.candidate_id
            WHERE u.id = auth.uid()
              AND u.role IN ('gm', 'recruiter', 'Manager', 'manager')
              AND (
                  u.role IN ('gm', 'recruiter')
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) > 0
                      AND c.position = ANY(u.allowed_positions)
                  )
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) = 0
                      AND u.department IS NOT NULL
                      AND btrim(u.department) <> ''
                      AND c.department = u.department
                  )
              )
        )
    );

DROP POLICY IF EXISTS "Internal users can add candidate notes" ON public.candidate_internal_notes;
CREATE POLICY "Internal users can add candidate notes"
    ON public.candidate_internal_notes
    FOR INSERT
    WITH CHECK (
        auth.role() = 'authenticated'
        AND created_by = auth.uid()
        AND EXISTS (
            SELECT 1
            FROM public.users u
            JOIN public.candidates c ON c.id = candidate_internal_notes.candidate_id
            WHERE u.id = auth.uid()
              AND u.role IN ('gm', 'recruiter', 'Manager', 'manager')
              AND (
                  u.role IN ('gm', 'recruiter')
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) > 0
                      AND c.position = ANY(u.allowed_positions)
                  )
                  OR (
                      COALESCE(array_length(u.allowed_positions, 1), 0) = 0
                      AND u.department IS NOT NULL
                      AND btrim(u.department) <> ''
                      AND c.department = u.department
                  )
              )
        )
    );

GRANT SELECT, INSERT ON public.candidate_internal_notes TO authenticated;
